name: Lint with Ruff

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff with selected rules and auto-fix
      run: ruff check dags/daily_*.py --fix --config .github/workflows/.ruff.toml
